version: '3'
services:
  stock-alert-schedule-app:
    image: "stock-alert-schedule-app"
    build: .
    container_name: "stock-alert-schedule-app"
    restart: always
    network_mode: host
    ports:
      - "8090:8090"
    volumes:
      - /opt/springboot/stock-alert-schedule/conf:/app/conf
      - /opt/springboot/logs/stock-alert-schedule:/logs/stock-alert-schedule


      
      
  
