## config

## spring config
spring:
  profiles:
    active: dev
  application:
    name: stock-alert
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-test-query: SELECT 1

## mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:mybatis/*.xml
  type-aliases-package: com.ljq.stock.alert.model.entity

## log
logging:
  level:
    com.ljq.stock.alert.dao: debug

## 异常日志栈深度
exceptionLogStackDepth: 5

## 股票数据接口
stockApi:
  apiSina: https://hq.sinajs.cn/list=
  apiTencent: https://sqt.gtimg.cn/q=
  apiNetease: https://api.money.126.net/data/feed/
  active: sina
  apiAllStockSina: https://vip.stock.finance.sina.com.cn/quotes_service/api/json_v2.php/Market_Center.getHQNodeData
  apiAllStockMyData: https://api.mairui.club/hslt/list/
  apiMyDataLicence: xxx


## 微信配置
wechat:
  mini:
    appId: xxxxx
    appSecret: xxxxx
    loginUrl: https://api.weixin.qq.com/sns/jscode2session
    msgToken: xxxxx
    msgAesKey: xxxxx

